
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package user.servidor.Cup;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int KEYC = 41;
  public static final int TEXTFIELD = 34;
  public static final int KEYA = 40;
  public static final int USERCREATOR = 17;
  public static final int ADDCOMPONENT = 23;
  public static final int EQUALS = 5;
  public static final int DELETETRIVIA = 21;
  public static final int CHECKBOX = 36;
  public static final int TEXTAREA = 35;
  public static final int DATE = 19;
  public static final int BRACKETC = 44;
  public static final int NEWTRIVIA = 8;
  public static final int EDREQUEST = 50;
  public static final int BRACKETA = 43;
  public static final int ENDREQ = 51;
  public static final int IDTRIVIA = 11;
  public static final int USERDATA = 42;
  public static final int COLUMN = 58;
  public static final int OPTIONSRESPONSES = 33;
  public static final int COMMA = 10;
  public static final int TIMEQUESTION = 15;
  public static final int VERSION = 4;
  public static final int EDRESPONSE = 54;
  public static final int TRIVIA = 25;
  public static final int GREATERT = 9;
  public static final int ID = 24;
  public static final int TXTVISIBLE = 27;
  public static final int INRESPONSE = 53;
  public static final int PARAMETERSTRIVIA = 45;
  public static final int EOF = 0;
  public static final int PARAMETERSCOMPONENT = 46;
  public static final int error = 1;
  public static final int RESPONSETRIVIA = 28;
  public static final int DATECREATION = 20;
  public static final int NUMBER = 16;
  public static final int OPENXS = 2;
  public static final int ENDRESPONSES = 56;
  public static final int EDITCOMPONENT = 30;
  public static final int CARDINEX = 38;
  public static final int EDITTRIVIA = 22;
  public static final int NAME = 14;
  public static final int DELETECOMPONENT = 29;
  public static final int ENDXS = 7;
  public static final int COLON = 12;
  public static final int RADIO = 37;
  public static final int INDEX = 31;
  public static final int THEME = 18;
  public static final int INITRESPONSES = 55;
  public static final int OPENREQ = 47;
  public static final int INREQUEST = 48;
  public static final int ROW = 57;
  public static final int COMBO = 39;
  public static final int CLASSTRIVIA = 26;
  public static final int ENDREQUESTS = 59;
  public static final int INITREQUESTS = 52;
  public static final int TEXT = 13;
  public static final int XSON = 3;
  public static final int LESST = 49;
  public static final int OPTIONS = 32;
  public static final int NUMBERVERSION = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPENXS",
  "XSON",
  "VERSION",
  "EQUALS",
  "NUMBERVERSION",
  "ENDXS",
  "NEWTRIVIA",
  "GREATERT",
  "COMMA",
  "IDTRIVIA",
  "COLON",
  "TEXT",
  "NAME",
  "TIMEQUESTION",
  "NUMBER",
  "USERCREATOR",
  "THEME",
  "DATE",
  "DATECREATION",
  "DELETETRIVIA",
  "EDITTRIVIA",
  "ADDCOMPONENT",
  "ID",
  "TRIVIA",
  "CLASSTRIVIA",
  "TXTVISIBLE",
  "RESPONSETRIVIA",
  "DELETECOMPONENT",
  "EDITCOMPONENT",
  "INDEX",
  "OPTIONS",
  "OPTIONSRESPONSES",
  "TEXTFIELD",
  "TEXTAREA",
  "CHECKBOX",
  "RADIO",
  "CARDINEX",
  "COMBO",
  "KEYA",
  "KEYC",
  "USERDATA",
  "BRACKETA",
  "BRACKETC",
  "PARAMETERSTRIVIA",
  "PARAMETERSCOMPONENT",
  "OPENREQ",
  "INREQUEST",
  "LESST",
  "EDREQUEST",
  "ENDREQ",
  "INITREQUESTS",
  "INRESPONSE",
  "EDRESPONSE",
  "INITRESPONSES",
  "ENDRESPONSES",
  "ROW",
  "COLUMN",
  "ENDREQUESTS"
  };
}

