
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package user.servidor.Cup;

/** CUP generated class containing symbol constants. */
public class UserParserSym {
  /* terminals */
  public static final int DELETEUSER = 17;
  public static final int INSTITUTION = 10;
  public static final int ENDREQ = 27;
  public static final int KEYC = 21;
  public static final int DATE = 11;
  public static final int NEWUSER = 2;
  public static final int XSON = 29;
  public static final int USERDATA = 19;
  public static final int KEYA = 18;
  public static final int NAME = 9;
  public static final int USER = 5;
  public static final int INREQUEST = 24;
  public static final int OLDUSER = 14;
  public static final int GREATERT = 3;
  public static final int COLON = 6;
  public static final int NEWPASSWORD = 15;
  public static final int DATEEDIT = 16;
  public static final int EDITUSER = 13;
  public static final int INITREQUESTS = 33;
  public static final int EQUALS = 31;
  public static final int OPENXS = 28;
  public static final int COMMA = 4;
  public static final int LESST = 25;
  public static final int EOF = 0;
  public static final int PASSWORD = 8;
  public static final int error = 1;
  public static final int BRACKETC = 22;
  public static final int VERSION = 30;
  public static final int BRACKETA = 20;
  public static final int TEXT = 7;
  public static final int OPENREQ = 23;
  public static final int EDREQUEST = 26;
  public static final int DATECREATION = 12;
  public static final int ENDREQUESTS = 34;
  public static final int ENDXS = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NEWUSER",
  "GREATERT",
  "COMMA",
  "USER",
  "COLON",
  "TEXT",
  "PASSWORD",
  "NAME",
  "INSTITUTION",
  "DATE",
  "DATECREATION",
  "EDITUSER",
  "OLDUSER",
  "NEWPASSWORD",
  "DATEEDIT",
  "DELETEUSER",
  "KEYA",
  "USERDATA",
  "BRACKETA",
  "KEYC",
  "BRACKETC",
  "OPENREQ",
  "INREQUEST",
  "LESST",
  "EDREQUEST",
  "ENDREQ",
  "OPENXS",
  "XSON",
  "VERSION",
  "EQUALS",
  "ENDXS",
  "INITREQUESTS",
  "ENDREQUESTS"
  };
}

