
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.proyect1.Cup;

/** CUP generated class containing symbol constants. */
public class LoginSym {
  /* terminals */
  public static final int NUMBERVERSION = 6;
  public static final int ENDREQ = 24;
  public static final int KEYC = 17;
  public static final int KEYA = 13;
  public static final int XSON = 3;
  public static final int USERDATA = 14;
  public static final int USER = 8;
  public static final int INREQUEST = 19;
  public static final int GREATERT = 21;
  public static final int COLON = 9;
  public static final int EQUALS = 5;
  public static final int OPENXS = 2;
  public static final int COMMA = 11;
  public static final int LESST = 22;
  public static final int EOF = 0;
  public static final int LOGINUSER = 20;
  public static final int PASSWORD = 12;
  public static final int error = 1;
  public static final int BRACKETC = 16;
  public static final int VERSION = 4;
  public static final int BRACKETA = 15;
  public static final int TEXT = 10;
  public static final int OPENREQ = 18;
  public static final int EDREQUEST = 23;
  public static final int ENDXS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPENXS",
  "XSON",
  "VERSION",
  "EQUALS",
  "NUMBERVERSION",
  "ENDXS",
  "USER",
  "COLON",
  "TEXT",
  "COMMA",
  "PASSWORD",
  "KEYA",
  "USERDATA",
  "BRACKETA",
  "BRACKETC",
  "KEYC",
  "OPENREQ",
  "INREQUEST",
  "LOGINUSER",
  "GREATERT",
  "LESST",
  "EDREQUEST",
  "ENDREQ"
  };
}

