
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package user.servidor.Cup.json;

/** CUP generated class containing symbol constants. */
public class UserJsonSym {
  /* terminals */
  public static final int DATE = 12;
  public static final int COLON = 6;
  public static final int USER = 8;
  public static final int EOF = 0;
  public static final int KEYC = 5;
  public static final int DATECREATION = 14;
  public static final int KEYA = 4;
  public static final int error = 1;
  public static final int COMMA = 7;
  public static final int TEXT = 13;
  public static final int INSTITUTION = 10;
  public static final int CORCHETEC = 3;
  public static final int CORCHETEA = 2;
  public static final int NAME = 11;
  public static final int PASSWORD = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CORCHETEA",
  "CORCHETEC",
  "KEYA",
  "KEYC",
  "COLON",
  "COMMA",
  "USER",
  "PASSWORD",
  "INSTITUTION",
  "NAME",
  "DATE",
  "TEXT",
  "DATECREATION"
  };
}

